# -*- coding: utf-8 -*-
"""Single source of truth for Pyramid Engineering website content.
Edit values here and re-run build.py to regenerate every page."""

COMPANY = {
    "name": "Pyramid Engineering Private Limited",
    "short": "Pyramid Engineering",
    "abbr": "PEPL",
    "tagline": "Your Maintenance and Project Solutions Partner",
    "founded": 2008,
    "uen": "200821275M",
    "address_line1": "10 Buroh Street",
    "address_line2": "West Connect Building #07-34",
    "address_city": "Singapore 627564",
    "address_full": "10 Buroh Street, West Connect Building #07-34, Singapore 627564",
    "phone_display": "+65 6259 9046",
    "phone_tel": "+6562599046",
    "whatsapp": "6562599046",
    "email": "enquiry@pyramid-groups.com",
    "email_admin": "admin@pyramid-groups.com",
    "website": "https://www.pyramid-groups.com",
    "domain": "www.pyramid-groups.com",
    "hours": [("Monday – Friday", "8:30 am – 6:00 pm"),
              ("Saturday", "8:30 am – 1:00 pm"),
              ("Sunday & Public Holidays", "Closed (24/7 breakdown support for contract clients)")],
    "linkedin": "#",
    "facebook": "#",
}

NAV = [
    ("Home", "index.html", None),
    ("About", "about.html", None),
    ("Services", "services.html", "SERVICES"),
    ("Sectors", "sectors.html", None),
    ("Projects", "projects.html", None),
    ("Certifications", "certifications.html", None),
    ("Contact", "contact.html", None),
]

# ---------------------------------------------------------------------------
# Services — slug, title, nav label, one-line, hero image, and page content
# ---------------------------------------------------------------------------
SERVICES = [
    {
        "slug": "electrical",
        "title": "Electrical Engineering",
        "nav": "Electrical Engineering",
        "menu_note": "HT/LT cabling, switchgear, LEW services",
        "img": "svc-electrical",
        "img_alt": "Pyramid Engineering electrician terminating multi-core power cable on site",
        "short": "HT and LT cabling, switchgear and power distribution installed, tested and commissioned to Singapore standards.",
        "meta": "Industrial electrical contractor in Singapore — HT/LT cabling, switchgear installation, testing, commissioning and Licensed Electrical Worker services.",
        "intro": "Electrical work in a live process plant is unforgiving: a mis-terminated core, an untested loop or an unpermitted isolation can cost days of production. Pyramid Engineering has installed, tested and energised electrical systems inside Singapore's refineries, petrochemical complexes and power stations since 2008 — working under permit, in hazardous areas, and very often around plant that cannot be shut down.",
        "capabilities": [
            ("Cabling and containment", [
                "High-voltage and low-voltage cable laying, glanding and termination",
                "Cable ladder, tray and trunking fabrication and installation",
                "Cable pulling through congested racks, trenches and duct banks",
                "Cable schedules, megger and continuity records for handover",
            ]),
            ("Switchgear and distribution", [
                "Supply and installation of HT and LT switchgear",
                "Power distribution panels, MCCs, distribution boards and isolators",
                "Motor installation, alignment support and terminations",
                "Busbar and interconnection works",
            ]),
            ("Testing, commissioning and compliance", [
                "Pre-commissioning checks, insulation resistance and earth-loop testing",
                "Functional testing, energisation and start-up support",
                "Licensed Electrical Worker (LEW) services for statutory sign-off",
                "As-built marking, test certificates and handover documentation",
            ]),
            ("Maintenance and supply", [
                "Preventive and corrective maintenance of panels and equipment",
                "Thermographic survey support and defect rectification",
                "Breakdown attendance under call-out agreements",
                "Supply of electrical materials, cables, fittings and spares",
            ]),
        ],
        "gallery": [("p-switchgear", "Low-voltage switchboard lineup prior to installation"),
                    ("p-elec-testing", "Thermographic inspection of a live distribution panel"),
                    ("p-switchboard", "Switchboard maintenance during a plant shutdown")],
        "standards": ["SS 638 : Code of Practice for Electrical Installations",
                      "SS 551 : Earthing and protection against electric shock",
                      "IEC 60079 : Explosive atmospheres — equipment and installation",
                      "Client plant electrical specifications and permit-to-work systems"],
        "applications": ["Refinery and petrochemical plant electrical packages",
                         "Power station shutdown and turnaround electrical works",
                         "Solar plant balance-of-system electrical installation",
                         "Small capital projects and plant modification tie-ins",
                         "Substation and MCC room upgrade works"],
        "outcomes": [
            ("Energised right the first time", "Loops, terminations and protection settings are proven before energisation, so start-up is not the first time a fault is discovered."),
            ("Statutory sign-off included", "LEW services mean the installation is certified as part of the same scope rather than becoming your problem at handover."),
            ("Built for live plant", "Crews work to your permit system, isolation procedures and hazardous-area classification as a matter of routine."),
        ],
    },
    {
        "slug": "control-instrumentation",
        "title": "Control & Instrumentation",
        "nav": "Control & Instrumentation",
        "menu_note": "Field instruments, panels, calibration, loop checks",
        "img": "svc-instrumentation",
        "img_alt": "Field transmitters and control valve assembly with a Fluke process calibrator connected",
        "short": "Field instruments, control panels, calibration and loop checking through to commissioning and DCS interface.",
        "meta": "C&I contractor in Singapore — instrument installation, bench and field calibration, loop checking, control panels and PLC/DCS commissioning support.",
        "intro": "Instrumentation is where a process plant's control philosophy meets physical reality. Pyramid Engineering designs, installs, calibrates and proves instrument and control systems — from a single replacement transmitter during a running shift to complete C&I packages on new units — and has done so for Chevron, Shell, ExxonMobil, Evonik, DuPont and REC Solar sites under main contractors including Kurihara Kogyo, KPW Engineering, Siemens and Honeywell.",
        "capabilities": [
            ("Instrument installation", [
                "Field transmitters, gauges, switches, thermowells and analysers",
                "Field junction boxes, marshalling and interface cabinets",
                "Impulse and pneumatic tubing, manifolds and hook-ups",
                "Control valve, actuator and positioner installation",
                "Safeguarding and interlock device installation",
            ]),
            ("Cabling and termination", [
                "Instrument and control cable laying, glanding and termination",
                "Segregated routing for intrinsically safe circuits",
                "Screen and earthing integrity verification",
                "Cable schedules and termination records",
            ]),
            ("Calibration and loop checking", [
                "Bench and field calibration of all instrument types",
                "Full loop checks — field device to DCS/PLC graphic",
                "Control valve stroking, positioner calibration and travel checks",
                "Calibration certificates and punch-list close-out",
            ]),
            ("Panels, systems and commissioning", [
                "Design, engineering and build of instrument and control panels",
                "PLC / DCS / SCADA interfacing, I/O checks and logic verification",
                "Pre-commissioning, commissioning and start-up support",
                "Troubleshooting and instrumentation maintenance contracts",
                "Supply of instruments, sensors, valves and spares",
            ]),
        ],
        "gallery": [("p-calibration", "Bench calibration of a pressure transmitter"),
                    ("p-inst-manifold", "Instrument manifold and impulse tubing installation"),
                    ("p-analyser", "Analyser panel installation and commissioning"),
                    ("p-control-valve", "Control valve and positioner installed on process line"),
                    ("p-inst-skid", "Field instrument hook-up on a process skid"),
                    ("p-commissioning", "Loop checking during plant commissioning")],
        "standards": ["ISA 5.1 / ISA 20 — instrumentation symbols and specification forms",
                      "IEC 61511 — functional safety for the process industry",
                      "IEC 60079 — installation in explosive atmospheres",
                      "Client loop folder, calibration and punch-list procedures"],
        "applications": ["Greenfield C&I packages on new process units",
                         "Turnaround instrument overhaul, calibration and loop re-checks",
                         "Obsolescence-driven instrument and control system replacement",
                         "Analyser and sampling system installation",
                         "Long-term instrumentation maintenance under call-out contract"],
        "outcomes": [
            ("Loops proven, not assumed", "Every loop is checked end-to-end to the operator graphic and signed off with a calibration record you can put in front of an auditor."),
            ("Four-year maintenance relationships", "Clients such as Ashahi Kokusai Keiso have kept our instrumentation crews embedded for years — because the same people know the plant."),
            ("Ready for the DCS", "I/O verification and logic checks happen before commissioning day, not during it."),
        ],
    },
    {
        "slug": "fire-gas-security",
        "title": "Fire & Gas and Security Systems",
        "seo_title": "Fire & Gas and Security",
        "nav": "Fire & Gas and Security",
        "menu_note": "Detection, alarm panels, CCTV and access control",
        "img": "svc-firegas",
        "img_alt": "Installed CCTV cameras, detection devices and security system components across an industrial facility",
        "short": "Fire and gas detection, alarm panels, CCTV and access control — supplied, installed and commissioned.",
        "meta": "Fire and gas detection and industrial security in Singapore — detectors, alarm panels, CCTV and access control supplied, installed and commissioned.",
        "intro": "Detection systems only earn their keep on the day something goes wrong. Pyramid Engineering supplies, installs and commissions fire and gas detection, alarm panels and security systems across process plants and industrial facilities — proving every device, every loop and every cause-and-effect action before the system is signed over to operations.",
        "capabilities": [
            ("Fire and gas detection", [
                "Flame, smoke, heat and combustible gas detector installation",
                "Manual call points, sounders and beacon installation",
                "Detector siting support and coverage verification",
                "Field device functional testing and gas bump testing",
            ]),
            ("Alarm and control panels", [
                "Fire and gas alarm panel supply and installation",
                "Panel wiring, addressing and loop configuration",
                "Cause-and-effect matrix verification",
                "Interface to DCS, ESD and plant annunciation systems",
            ]),
            ("Security systems", [
                "CCTV camera supply, installation and alignment",
                "Network video recorders, storage and monitoring stations",
                "Access control devices and door hardware integration",
                "Perimeter and gatehouse security installations",
            ]),
            ("Commissioning and support", [
                "End-to-end functional and integration testing",
                "As-built documentation and device schedules",
                "Operator familiarisation and handover",
                "Scheduled inspection, testing and maintenance",
            ]),
        ],
        "gallery": [("svc-firegas", "Security and detection devices installed across a client facility")],
        "standards": ["SS CP 10 — installation and servicing of fire alarm systems",
                      "SS 645 — code of practice for CCTV systems",
                      "IEC 60079 — hazardous-area equipment and installation",
                      "Client fire and gas philosophy and cause-and-effect matrices"],
        "applications": ["Process plant fire and gas detection upgrades",
                         "Building and facility fire alarm system installation",
                         "Site-wide CCTV and access control roll-outs",
                         "Carpark, warehouse and gatehouse security installations",
                         "Detection system replacement during turnarounds"],
        "outcomes": [
            ("Cause and effect, verified", "We test the action, not just the device — every initiating input is proven against its intended output."),
            ("One contractor for detection and power", "Because we also do the electrical and instrumentation scope, the interfaces are ours to get right."),
            ("Documented for the authorities", "Device schedules, test records and as-builts are produced as part of the work."),
        ],
    },
    {
        "slug": "mechanical-piping",
        "title": "Mechanical & Piping",
        "nav": "Mechanical & Piping",
        "menu_note": "Piping, supports, valves, QA/QC inspection",
        "img": "svc-mechanical",
        "img_alt": "Heat exchanger and large-bore process piping in an industrial plant with technician in attendance",
        "short": "Piping prefabrication and installation, supports, mechanical valves and QA/QC inspection services.",
        "meta": "Mechanical and piping contractor in Singapore — pipe spool prefabrication, piping and support installation, equipment erection and QA/QC inspection.",
        "intro": "Pyramid Engineering's mechanical crews prefabricate and install process piping, supports and valves for oil and gas, petrochemical and chemical plants — with the fabrication, surface preparation, coating, insulation and non-destructive examination coordinated as one package rather than left as loose ends between trades.",
        "capabilities": [
            ("Piping works", [
                "Prefabrication of pipe spools in shop conditions",
                "Installation of process, utility and instrument piping",
                "Pipe support fabrication, installation and adjustment",
                "Hydrotesting support, flushing and reinstatement",
            ]),
            ("Equipment", [
                "Installation of static equipment — vessels, exchangers, columns",
                "Rotating equipment installation and alignment support",
                "Fabrication and erection of steel structures and fixed equipment",
                "Prefabrication of pre-assembled modules (PAM) and skids",
            ]),
            ("Valves and specialities", [
                "Installation and maintenance of mechanical valves",
                "Valve overhaul coordination during turnarounds",
                "Specialty item installation and gasket management",
            ]),
            ("Quality and support services", [
                "QA/QC inspection services and documentation",
                "Non-destructive examination (NDE) coordination",
                "Surface preparation, blasting and coating management",
                "Construction management and plant commissioning support",
            ]),
        ],
        "gallery": [("p-welding", "Pipe spool welding in the fabrication shop"),
                    ("p-spools", "Prefabricated pipe spools ready for site installation"),
                    ("p-process-piping", "Installed process piping and supports in a running plant")],
        "standards": ["ASME B31.3 — process piping",
                      "ASME Section IX — welding and brazing qualifications",
                      "ASME Section V / client NDE procedures",
                      "Client piping specifications, line lists and isometrics"],
        "applications": ["Process unit piping packages and tie-ins",
                         "Turnaround piping replacement and repair scopes",
                         "Skid and pre-assembled module fabrication",
                         "Utility and steam line installation",
                         "Small capital projects and plant modifications"],
        "outcomes": [
            ("Shop-built where it counts", "Prefabrication moves welding off the critical path and out of congested live areas."),
            ("Trade interfaces owned", "Insulation, coating and NDE sit inside the same scope, so nothing waits on another contractor's mobilisation."),
            ("Inspection-ready records", "Weld maps, NDE reports and test packs are assembled as the work proceeds."),
        ],
    },
    {
        "slug": "thermal-insulation",
        "title": "Thermal Insulation",
        "nav": "Thermal Insulation",
        "menu_note": "Hot & cold services, cladding, equipment insulation",
        "img": "svc-insulation",
        "img_alt": "Metal-clad thermal insulation on large-bore process pipework and elbows in a plant",
        "short": "Hot and cold service insulation for process piping, vessels and equipment, with fabrication and cladding.",
        "meta": "Thermal insulation contractor in Singapore — hot and cold service insulation, cladding and jacketing for process piping, vessels, tanks and boilers.",
        "intro": "Insulation is the quietest line item on an energy bill and one of the most expensive to get wrong — poor cold-service detailing invites corrosion under insulation, and poor hot-service work bleeds heat and creates burn hazards. Pyramid Engineering has insulated process piping, vessels, tanks and boilers across Singapore's chemical and refinery sites, and it remains one of the disciplines clients return to us for by name.",
        "capabilities": [
            ("Hot service insulation", [
                "Process piping, steam lines and headers",
                "Vessels, columns, exchangers and boilers",
                "Personnel protection insulation for hot surfaces",
                "Furnace, duct and breeching insulation",
            ]),
            ("Cold service insulation", [
                "Chilled water, refrigerant and cryogenic line insulation",
                "Vapour barrier detailing to prevent moisture ingress",
                "Cold box and low-temperature equipment insulation",
                "Detailing to limit corrosion under insulation (CUI) risk",
            ]),
            ("Cladding and fabrication", [
                "Aluminium and stainless steel cladding and jacketing",
                "In-house fabrication of fittings, elbows, valve boxes and covers",
                "Removable and re-usable insulation covers for maintained items",
                "Acoustic insulation for noise attenuation",
            ]),
            ("Consultancy and supply", [
                "Technical consultancy on insulation systems and thickness",
                "Procurement and supply of all insulation material types",
                "Energy-efficiency improvement surveys and remediation",
                "Turnaround strip-out, inspection and reinstatement",
            ]),
        ],
        "gallery": [("p-insulated-vessel", "Insulated and clad vessels with valve assemblies"),
                    ("p-insulated-plant", "Clad insulation on plant pipework and equipment"),
                    ("p-furnace-headers", "Insulated furnace headers inside a process plant")],
        "standards": ["ASTM C547 / C591 / C552 — insulation material specifications",
                      "BS 5970 — thermal insulation of pipework and equipment",
                      "CINI / client insulation standards for cladding detail",
                      "Client CUI-prevention and vapour-barrier specifications"],
        "applications": ["Refinery and petrochemical hot and cold service systems",
                         "Power plant steam, condensate and boiler insulation",
                         "Cryogenic and industrial gas plant cold boxes",
                         "Chemical plant reactors, vessels and exchangers",
                         "Turnaround insulation removal, inspection and reinstatement"],
        "outcomes": [
            ("Detailing that keeps water out", "Cold-service vapour barriers and cladding laps are where insulation jobs fail — we detail them deliberately."),
            ("Fabrication in-house", "Fittings, covers and valve boxes are made to suit the item rather than forced from stock shapes."),
            ("Named in client testimonials", "Hitachi, FieldCore and Kim Hock have all cited insulation as the reason they keep us on site."),
        ],
    },
    {
        "slug": "refractory-lining",
        "title": "Refractory Lining",
        "nav": "Refractory Lining",
        "menu_note": "Furnaces, boilers, reactors, casting and relining",
        "img": "svc-refractory",
        "img_alt": "Refractory casting work in progress on a large industrial vessel section",
        "short": "Monolithic and brick refractory for furnaces, boilers and reactors — installation, repair and relining.",
        "meta": "Refractory contractor in Singapore — monolithic and brick lining for furnaces, boilers, reactors and incinerators, with inspection, repair and relining.",
        "intro": "Refractory failure takes a furnace offline and keeps it there. Pyramid Engineering installs, repairs and relines refractory in furnaces, boilers, reactors and incinerators — monolithic and brick, including erosion-resistant and acid-resistant systems — with inspection and technical consultancy to establish what actually needs replacing before a shutdown window opens.",
        "capabilities": [
            ("Installation systems", [
                "Monolithic linings — castable, gunning and ramming mixes",
                "Brick and non-monolithic refractory lining",
                "Erosion-resistant and acid-resistant refractory",
                "Ceramic fibre and insulating back-up linings",
            ]),
            ("Equipment covered", [
                "Furnaces, heaters and boiler enclosures",
                "Reactors, regenerators and cyclones",
                "Incinerators, ducts and breeching",
                "Stacks, flues and transfer lines",
            ]),
            ("Execution", [
                "Casting work with formwork design and anchor installation",
                "Gunning and shotcreting for large surface areas",
                "Controlled dry-out and cure schedules",
                "Hot and cold repair of localised damage",
            ]),
            ("Inspection and supply", [
                "Inspection and technical consultancy for refractory systems",
                "Supply of refractory materials and anchors",
                "Condition survey and remaining-life assessment",
                "Turnaround relining planning and execution",
            ]),
        ],
        "gallery": [("p-refractory-lining", "Brick refractory lining inside a cylindrical vessel"),
                    ("p-refractory-duct", "Refractory-lined duct interior after relining")],
        "standards": ["API 936 — refractory installation, inspection and testing",
                      "ASTM C113 / C133 — refractory testing methods",
                      "Manufacturer dry-out and cure schedules",
                      "Client refractory specifications and anchor drawings"],
        "applications": ["Refinery fired heater and furnace relining",
                         "Boiler and incinerator refractory replacement",
                         "Reactor and cyclone erosion-resistant lining",
                         "Emergency hot repairs to limit unplanned outage",
                         "Turnaround refractory scopes on critical path"],
        "outcomes": [
            ("Shutdown-window discipline", "Refractory is almost always on the critical path — planning, anchors and dry-out are scheduled backwards from your start-up date."),
            ("Repair before replace", "Inspection first means you spend on the lining that has actually failed, not the whole vessel."),
            ("Client-verified", "Hileck Engineering and Kim Hock have both credited our refractory work with extending equipment life and cutting downtime."),
        ],
    },
    {
        "slug": "civil-works",
        "title": "General Civil Works",
        "nav": "General Civil Works",
        "menu_note": "Cable trenches, duct banks, plinths, roadworks",
        "img": "svc-civil",
        "img_alt": "Civil works crew constructing reinforced concrete works on an industrial site",
        "short": "Cable trenches, duct banks, equipment plinths and plant roadworks supporting electrical and mechanical scopes.",
        "meta": "Industrial civil works in Singapore — cable trenches, duct banks, equipment plinths, road crossings and plant roadworks inside operating facilities.",
        "intro": "Most of our civil work exists to make an electrical or mechanical scope possible: the trench the cable runs in, the plinth the panel stands on, the road crossing that lets a feeder reach the far side of a plant. Keeping that work in the same hands removes the interface that usually delays it.",
        "capabilities": [
            ("Underground routes", [
                "Cable trench excavation, construction and reinstatement",
                "Duct bank construction and encasement",
                "Road crossing works for underground cabling",
                "Pull-pit and manhole construction",
            ]),
            ("Foundations and plinths", [
                "Equipment and panel plinth construction",
                "Pump, skid and package foundation works",
                "Steel base plate grouting and levelling",
            ]),
            ("Roads and paving", [
                "Road widening, extension and re-marking",
                "Road maintenance and patch works in plant operating areas",
                "Hardstanding and access route construction",
            ]),
            ("Drainage and general", [
                "Construction and maintenance of road drainage",
                "Concrete repair and general builder's work",
                "Reinstatement following installation works",
            ]),
        ],
        "gallery": [("p-civil-rebar", "Reinforcement fixing for a plant slab"),
                    ("p-civil-slab", "Completed concrete slab within an operating plant"),
                    ("p-civil-crew", "Civil crew executing works inside a live facility")],
        "standards": ["SS EN 1992 / BS 8110 — structural concrete design and practice",
                      "SS EN 206 — concrete specification and conformity",
                      "Client plant excavation permit and buried-services procedures",
                      "WSH (Construction) Regulations"],
        "applications": ["Cable route civil works for electrical packages",
                         "Foundations for new panels, skids and packages",
                         "Plant road and drainage maintenance",
                         "Reinstatement after underground cable installation",
                         "Small capital project civil scopes"],
        "outcomes": [
            ("No interface delay", "The crew laying your cable and the crew building the trench answer to the same project manager."),
            ("Live-plant excavation discipline", "Buried-services checks, permits and reinstatement are handled to plant procedure."),
            ("Right-sized for plant work", "Small, self-sufficient teams suited to congested operating areas rather than open construction sites."),
        ],
    },
    {
        "slug": "maintenance-shutdown",
        "title": "Maintenance & Shutdown Support",
        "nav": "Maintenance & Shutdown",
        "menu_note": "Turnarounds, call-outs, planned maintenance",
        "img": "svc-maintenance",
        "img_alt": "Instrumentation technicians working on plant control and electrical systems during maintenance",
        "short": "Turnaround, shutdown, planned and breakdown maintenance under long-term contracts and call-out agreements.",
        "meta": "Plant maintenance and shutdown support in Singapore — turnarounds, preventive maintenance, call-out agreements and small capital projects for process plants.",
        "intro": "Pyramid Engineering was built around maintenance, and it is still the majority of what we do. Our teams have supported shutdowns at Shell Pulau Bukom, ExxonMobil Asia Pacific, Senoko, Tuas and Keppel Merlimau, and have held continuous maintenance positions at plants including Murata Electronics since 2012 and Chemical Speciality since 2021. Engineering staff are offered under long-term contracts, call-out agreements and routine maintenance agreements.",
        "capabilities": [
            ("Turnaround and shutdown", [
                "Shutdown scope development and pre-fabrication planning",
                "Multi-discipline execution teams mobilised to schedule",
                "Insulation strip-out, inspection support and reinstatement",
                "Instrument overhaul, calibration and loop re-checking",
                "Start-up assistance and punch-list close-out",
            ]),
            ("Planned maintenance", [
                "Maintenance planning and scheduling support",
                "Predictive and preventive maintenance programmes",
                "Daily and routine maintenance under term contracts",
                "Facilities maintenance for plant buildings and utilities",
            ]),
            ("Breakdown and call-out", [
                "Call-out agreements with defined response commitments",
                "Fault diagnosis across electrical, C&I and mechanical systems",
                "Temporary repair and permanent rectification",
            ]),
            ("Small capital projects", [
                "Plant modifications and tie-in works",
                "Obsolescence replacement and system upgrades",
                "Package installation and integration",
                "Equipment management — availability, condition and safe working order",
            ]),
        ],
        "gallery": [("p-commissioning", "Maintenance crew working on plant instrumentation"),
                    ("p-plant-structure", "Process plant structure prepared for shutdown access"),
                    ("p-scaffold-tower", "Scaffold access erected to a process column")],
        "standards": ["Client permit-to-work and isolation (LOTO) procedures",
                      "WSH Act and Workplace Safety and Health (Risk Management) Regulations",
                      "ISO 45001:2018 occupational health and safety management",
                      "Client turnaround planning and quality assurance procedures"],
        "applications": ["Refinery and petrochemical turnarounds",
                         "Power station shutdown maintenance campaigns",
                         "Long-term embedded maintenance teams",
                         "Emergency breakdown response",
                         "Rolling small capital project programmes"],
        "outcomes": [
            ("Crews that already know your plant", "Multi-year maintenance contracts mean the technician attending your breakdown has seen the loop before."),
            ("One mobilisation, several disciplines", "Electrical, C&I, mechanical, insulation and refractory scopes covered by one contractor under one permit."),
            ("Schedule is the deliverable", "In a shutdown, being right late is the same as being wrong — planning starts from the start-up date."),
        ],
    },
]

# ---------------------------------------------------------------------------
# Sectors
# ---------------------------------------------------------------------------
SECTORS = [
    {
        "slug": "refineries",
        "name": "Refineries",
        "img": "hero-plant",
        "short": "Turnaround and project execution inside Singapore's refining complexes.",
        "scope": ["Turnaround electrical, instrumentation and insulation scopes",
                  "Piping replacement, tie-ins and hydrotest support",
                  "Fired heater and furnace refractory relining",
                  "Instrument overhaul, calibration and loop re-checks",
                  "Start-up assistance and punch-list close-out"],
        "standards": ["ASME B31.3", "API 936", "IEC 60079", "SS 638"],
        "clients": ["Shell Eastern Petroleum — Pulau Bukom turnarounds",
                    "ExxonMobil Asia Pacific — turnaround campaigns",
                    "Singapore Refinery Complex — turnaround projects"],
    },
    {
        "slug": "petrochemical",
        "name": "Petrochemical & Chemical",
        "img": "p-process-piping",
        "short": "Multi-discipline project and maintenance work across Jurong Island chemical plants.",
        "scope": ["Electrical and C&I packages for new and modified units",
                  "Hot and cold service thermal insulation",
                  "Mechanical piping, supports and equipment installation",
                  "Reactor and vessel refractory lining",
                  "Embedded maintenance teams under term contract"],
        "standards": ["ASME B31.3", "IEC 61511", "ASTM C547 / C591", "IEC 60079"],
        "clients": ["Chevron Ornite — carboxylate and tank farm projects",
                    "Evonik ME06 / Linde IGP-2 — project works",
                    "DuPont Sakra — utilities separation project",
                    "Sumitomo Chemicals, Kuraray, Denka, Solvay, Lanxess"],
    },
    {
        "slug": "power",
        "name": "Power Generation",
        "img": "power-station",
        "short": "Shutdown maintenance and support across Singapore's generation fleet.",
        "scope": ["Shutdown maintenance for cogeneration and thermal plants",
                  "Electrical and instrumentation maintenance and overhaul",
                  "Steam and condensate system thermal insulation",
                  "Boiler refractory inspection and repair",
                  "Operations and maintenance support personnel"],
        "standards": ["SS 638", "IEC 60079", "BS 5970", "ISO 45001:2018"],
        "clients": ["Senoko Power Station — shutdown maintenance works",
                    "Tuas Power Plant — maintenance support",
                    "Keppel Merlimau Cogen — shutdown maintenance",
                    "Sembcorp Cogen Banyan — shutdown maintenance",
                    "Pacific Light Cogen, PowerSeraya, SUT EfW"],
    },
    {
        "slug": "renewables",
        "name": "Renewables & Solar",
        "img": "consult",
        "short": "Electrical and control scopes on solar generation and revamp projects.",
        "scope": ["Balance-of-system electrical installation",
                  "Instrumentation and monitoring system installation",
                  "Cable routing, trenching and termination",
                  "Testing, commissioning and energisation support",
                  "Ongoing electrical and C&I maintenance"],
        "standards": ["SS 638", "SS 551", "IEC 62446", "ISO 9001:2015"],
        "clients": ["REC Solar Pte Ltd — revamp projects and ongoing maintenance",
                    "Sembcorp Solar — project works under Kurihara Kogyo"],
    },
    {
        "slug": "pharmaceutical",
        "name": "Pharmaceutical & Life Sciences",
        "img": "p-analyser",
        "short": "Controlled-environment electrical, instrumentation and civil scopes.",
        "scope": ["Instrument and control installation to GMP-aware standards",
                  "Electrical installation in classified and clean areas",
                  "Utility and process skid installation",
                  "Documentation packages supporting qualification",
                  "Scaffolding and access for plant maintenance"],
        "standards": ["ISA 5.1", "IEC 61511", "SS 638", "Client GMP procedures"],
        "clients": ["Pfizer — project works under KPW Engineering",
                    "Sanofi — civil works", "Croda N2 skid project"],
    },
    {
        "slug": "manufacturing",
        "name": "Manufacturing & Industrial Plants",
        "img": "p-switchgear",
        "short": "Long-running maintenance and small capital projects for manufacturers.",
        "scope": ["Plant electrical and instrumentation maintenance",
                  "Small capital projects and facility modifications",
                  "Fire, gas and security system installation",
                  "Facilities maintenance and equipment management",
                  "Civil works, plinths and cable routes"],
        "standards": ["SS 638", "SS CP 10", "ISO 9001:2015", "WSH Regulations"],
        "clients": ["Murata Electronics Singapore — ongoing since 2012",
                    "Kim Hock Corporation — project and maintenance works",
                    "Global Foundries — project works under Siemens",
                    "Micron — capital projects under Siemens"],
    },
    {
        "slug": "storage",
        "name": "Terminals, Storage & Utilities",
        "img": "p-tank-shell",
        "short": "Tank farm, terminal and industrial gas facility works.",
        "scope": ["Tank farm electrical and instrumentation works",
                  "Tank cleaning, desludging and hydrojetting",
                  "Insulation and cladding for storage and transfer systems",
                  "Terminal maintenance and shutdown support",
                  "Industrial gas plant project works"],
        "standards": ["API 653 (support scopes)", "IEC 60079", "SS 638", "WSH confined space requirements"],
        "clients": ["Vopak Sebarok — terminal project works",
                    "Air Liquide — maintenance and operation support",
                    "Linde IGP-2 — industrial gas plant projects",
                    "Advario — terminal client"],
    },
]

# ---------------------------------------------------------------------------
# Projects — (name, client/main contractor, sector keys, period, scope)
# ---------------------------------------------------------------------------
PROJECTS = [
    ("SMAG maintenance support", "Under Ashahi Kokusai Keiso", "manufacturing", "2019 Mar – present", "Continuous maintenance support, instrumentation and control systems."),
    ("Murata Electronics Singapore", "Murata Electronics Singapore (Pte) Ltd", "manufacturing", "2012 – present", "Ongoing plant electrical, instrumentation and facilities maintenance."),
    ("Pfizer plant project", "Under KPW Engineering", "pharmaceutical", "2023 Feb – present", "Electrical and instrumentation installation works."),
    ("Kim Hock Corporation project", "Kim Hock Corporation Ltd", "manufacturing", "2023 Feb – present", "Electrical, control and instrumentation project works."),
    ("Chemical Speciality maintenance", "Chemical Speciality S Pte Ltd", "petrochemical", "2021 Jan – 2023 Dec", "Plant maintenance works across electrical and instrumentation disciplines."),
    ("Sembcorp solar project", "Under Kurihara Kogyo Co Ltd", "renewables power", "2023 Jan – 2023 Mar", "Solar plant electrical installation works."),
    ("REC Solar revamp projects", "REC Solar Pte Ltd", "renewables", "2022 May – present", "Electrical and control instrumentation revamp and ongoing maintenance."),
    ("Global Foundries project", "Under Siemens", "manufacturing", "2023 Jan – present", "Electrical and instrumentation project execution."),
    ("Micron capital projects", "Under Siemens", "manufacturing", "2022 Oct – present", "Capital project electrical and instrumentation works."),
    ("Maintenance &amp; operation support — Exxon Mobil, Aster Bukom &amp; Seraya", "Air Liquide", "refineries storage", "2023 Feb – 2024 Apr", "Multi-site maintenance and operations support works."),
    ("Croda N2 skid project", "Under KPW Engineering", "petrochemical", "2021 Dec – 2022 Jan", "Nitrogen skid installation and commissioning support."),
    ("Maintenance &amp; SDM support to JML", "Pacific Light Cogen, PowerSeraya, Sembcorp Cogen Banyan, Senoko, SUT EfW", "power", "2022 Apr – present", "Shutdown and routine maintenance support across five generation plants."),
    ("Maintenance support under GE-FieldCore &amp; Hitachi", "Keppel Merlimau Cogen, Senoko Power Station, Sembcorp Cogen Banyan, Tuas Power Plant", "power", "2021 Apr – present", "Maintenance support across four power generation facilities."),
    ("Senoko Power Station shutdown", "Senoko Power Station", "power", "2022 Feb – 2022 May", "Shutdown maintenance works."),
    ("Sembcorp Cogen shutdown", "Under GE FieldCore", "power", "2022 Feb – 2022 Mar", "Shutdown maintenance works."),
    ("Keppel Merlimau Cogen shutdown", "Under GE FieldCore", "power", "2021 Oct – 2022 Feb", "Shutdown maintenance works."),
    ("Chevron Ornite — COPL FEP W-1", "Under Kurihara Kogyo Co Ltd", "petrochemical", "2021 Aug – 2021 Oct", "Project execution works for the COPL FEP W-1 package."),
    ("Vopak Sebarok terminal works", "Under Vac-Tech Engineering", "storage", "2019 Aug – 2019 Oct", "Terminal electrical and instrumentation works."),
    ("Vopak Sebarok terminal works", "Under Assure Engineering", "storage", "2019 Nov – 2020 Jan", "Terminal project works."),
    ("SRC project", "Under Vac-Tech Engineering", "refineries", "2019 May – 2019 Aug", "Refinery project works."),
    ("Evonik ME06 / Linde IGP-2", "Under KPW Engineering", "petrochemical storage", "2018 Apr – 2019 Mar", "ME06-IGP2 project — electrical, instrumentation and insulation scopes."),
    ("SJI maintenance", "Under Hertel", "petrochemical", "2016 Mar – 2019 Feb", "Long-term plant maintenance works."),
    ("Chevron Ornite — carboxylate project", "Under Kurihara Kogyo Co Ltd", "petrochemical", "2016 Mar – 2017 Oct", "Carboxylate project execution."),
    ("SUT project", "Under Everstar Engineering", "power", "2016 Mar – 2017 Oct", "Plant project works."),
    ("Chevron Ornite — carboxylate phase I", "Under Kurihara Kogyo Co Ltd", "petrochemical", "2015 Mar – 2015 Oct", "Carboxylate project, phase I."),
    ("DuPont Sakra — utilities separation", "Under Kurihara Kogyo Co Ltd", "petrochemical", "2014 Dec – 2015 May", "Utilities separation project execution."),
    ("Evonik ME05 project", "Under Austin Energy", "petrochemical", "2014 Apr – 2015 Mar", "Project works."),
    ("Tate &amp; Lyle project", "Under Kurihara Kogyo Co Ltd", "manufacturing", "2014 Jun – 2014 Nov", "Plant project execution."),
    ("Lanxess II project", "Under Kurihara Kogyo Co Ltd", "petrochemical", "2014 Jun – 2014 Nov", "Lanxess II project works."),
    ("Chevron Ornite — tank farm facilities", "Under Kurihara Kogyo Co Ltd", "petrochemical storage", "2013 Jan – 2014 Sep", "Tank farm facilities project."),
    ("Shell Eastern Petroleum — Pulau Bukom turnaround", "Under Industrial Services P Ltd", "refineries", "2014 Feb – 2014 Apr", "Refinery turnaround execution works."),
    ("Shell Bukom — Scot Bugis project", "Under Industrial Services P Ltd", "refineries", "2012 Nov – 2013 Mar", "Refinery project works."),
    ("SJI MEG turnaround &amp; project", "Under Industrial Services P Ltd", "petrochemical", "2012 Nov – 2013 Feb", "Turnaround and project execution."),
    ("Nalco project", "Under JML", "petrochemical", "2013 Oct – 2013 Dec", "Pipeline works from SUT to Nalco."),
    ("Kuraray turnaround &amp; project", "Under JML", "petrochemical", "2013 Oct – 2013 Nov", "Turnaround and project works."),
    ("Sembcorp Mucchi project", "Under JML", "power", "2013 Aug – 2013 Oct", "Plant project works."),
    ("JAC — Essar project", "Under Industrial Services P Ltd", "petrochemical", "2013 May – 2013 Jul", "Tank insulation and cladding works."),
    ("ExxonMobil Asia Pacific", "Under Industrial Services P Ltd", "refineries", "2013 Feb – 2013 Jun", "Turnaround and project works."),
    ("CCDS project", "Under Industrial Services P Ltd", "petrochemical", "2013 Jan – 2013 Jun", "Project execution works."),
    ("ExxonMobil Asia Pacific", "Under Industrial Services P Ltd", "refineries", "2012 Aug – 2012 Oct", "Turnaround and project works."),
    ("Chevron Ornite turnaround", "Under Industrial Services P Ltd", "petrochemical", "2012 Jul – 2012 Aug", "Turnaround and project execution works."),
    ("Tuas Incinerator Plant turnaround", "Under Industrial Services P Ltd", "power", "2012 Jul – 2012 Aug", "Turnaround and project works."),
    ("Chevron Ornite project works", "Under Kurihara Kogyo Co Ltd", "petrochemical", "2011 Nov – 2012 Mar", "Plant project execution."),
    ("Singapore Refinery Complex turnaround", "Under Industrial Services P Ltd", "refineries", "2011 Dec – 2012 Feb", "Refinery turnaround project."),
    ("Tuas Incinerator Plant turnaround", "Under Industrial Services P Ltd", "power", "2011 May – 2011 Oct", "Turnaround project works."),
    ("SUT project", "Under JML", "power", "2011 Aug – 2012 Jan", "Plant project works."),
    ("Singapore Refinery Complex turnaround", "Under Industrial Services P Ltd", "refineries", "2010 Nov – 2011 Apr", "Refinery turnaround project."),
    ("Shell Eastern Petroleum — Pulau Bukom turnaround", "Under Industrial Services P Ltd", "refineries", "2010 Sep – 2010 Oct", "Refinery turnaround works."),
    ("ExxonMobil Asia Pacific turnaround", "Under Industrial Services P Ltd", "refineries", "2009 Oct – 2010 Apr", "Refinery turnaround project."),
    ("DuPont Singapore — Adipure de-bottlenecking", "Under Kurihara Kogyo Co Ltd", "petrochemical", "2009 Apr – 2009 Nov", "De-bottlenecking project execution."),
    ("Chevron Ornite — detergent soap plant", "Under Kurihara Kogyo Co Ltd", "petrochemical", "2009 Jan – 2009 Jul", "Detergent soap plant project."),
    ("Romax Singapore project", "Under Kurihara Kogyo Co Ltd", "manufacturing", "2008 – 2010", "Plant project execution works."),
]

SECTOR_LABELS = {
    "refineries": "Refineries",
    "petrochemical": "Petrochemical & Chemical",
    "power": "Power Generation",
    "renewables": "Renewables & Solar",
    "pharmaceutical": "Pharmaceutical",
    "manufacturing": "Manufacturing",
    "storage": "Terminals & Storage",
}

# ---------------------------------------------------------------------------
# Testimonials (verbatim from client references in the company profile)
# ---------------------------------------------------------------------------
TESTIMONIALS = [
    ("Electrical &amp; Control Instrumentation",
     "Working with Pyramid on our electrical and control instrumentation needs has been a game-changer. Their attention to detail and expertise have not only improved the efficiency of our operations but also boosted our confidence in the reliability of our systems. We're proud to have them as a partner.",
     "Mr Gridhar", "Project Manager, Kurihara Kogyo Co Ltd"),
    ("Thermal Insulation",
     "The thermal insulation solutions offered by Pyramid have been a key component of our projects. Their dedication to precision and safety has made a significant difference in our industry. We value their partnership and look forward to continued success together.",
     "Mr Pazhani", "Project Manager, Hitachi Singapore"),
    ("Control Instrumentation",
     "Pyramid people have been invaluable assets to our company, contributing their expertise in instrumentation maintenance for the past four years. Their dedication, combined with our company's commitment to excellence, ensures the reliability and efficiency of our systems, reducing downtime and maximising productivity.",
     "Mr Edmund", "Site Manager, Ashahi Kokusai Keiso Co Ltd"),
    ("Electrical &amp; Control Instrumentation",
     "REC Solar Pte Ltd has had the privilege of collaborating with Pyramid for both new project completions and regular maintenance in electrical and control instrumentation for several years. Their unwavering commitment to quality and professionalism has consistently exceeded our expectations.",
     "Mr Sivakumar", "Operation Manager, REC Solar Pte Ltd"),
    ("Refractory",
     "The refractory solutions offered by Pyramid have played a vital role in maintaining the integrity of our industrial furnaces and equipment. Their expertise in refractory materials and installation has saved us time and money. We highly recommend their services.",
     "Mr Balu", "Site Manager, Hileck Engineering"),
    ("Civil Works",
     "The civil work provided by Pyramid has been instrumental in our infrastructure projects. Their commitment to quality, timely delivery, and attention to detail is commendable. We trust their team to bring our visions to life.",
     "Mr Pandian", "Project Manager, Sanofi"),
    ("Thermal Insulation",
     "We have entrusted Pyramid with our thermal insulation needs, and they consistently deliver top-notch results. Their work not only enhances our energy efficiency but also guarantees a safer work environment for our team.",
     "Mr Saravanan", "Project Manager, FieldCore Singapore"),
    ("Refractory",
     "Pyramid's refractory solutions are vital for maintaining our equipment integrity. Their expertise in materials and installation saves us time and money. We highly recommend their invaluable support.",
     "Mr Goh Seng", "Project Manager, Kim Hock Corporation Ltd"),
]

CLIENTS = ["Air Liquide", "GE-FieldCore", "Hitachi Singapore", "Kim Hock Corporation Ltd",
           "REC Solar Pte Ltd", "Sumitomo Chemicals (S) Ltd", "Kuraray Chemicals", "Advario"]

CONTRACTORS = ["Ashahi Kokusai Keiso Co", "Enercon Engineering", "Hileck Engineering",
               "Hertel Singapore", "Honeywell Singapore", "Industrial Services",
               "KPW Singapore", "Kurihara Kogyo Co", "PEC Ltd", "Siemens",
               "Unipower Engineering", "Vac-Tech Engineering Pte Ltd"]

PLANTS = ["Chevron Ornite", "Chemicals Speciality Ltd", "Denka", "Evonik ME06", "Giiava",
          "Invista Singapore", "JAC", "KMC – GE", "Kuraray", "Linde IGP2", "MEG", "Nalco",
          "Senoko Power Station", "Shell Chemicals", "Solvay Plant", "Sumitomo Chemicals",
          "Tuas Power Station", "Vopak (Sebarok)"]

CERTIFICATIONS = [
    {"img": "cert-iso9001", "title": "ISO 9001:2015 — Quality Management",
     "body": "Certificate No. 24EQMV39. Initially registered 26 February 2024, issued 26 February 2024, valid to 25 February 2027. Scope: process and industrial plant consultancy, engineering, construction and maintenance works for chemical, refineries and petrochemical industries. Accredited under EGAC / IAF."},
    {"img": "cert-iso45001", "title": "ISO 45001:2018 — Occupational Health &amp; Safety",
     "body": "Certificate No. 24EOMV46. Initially registered 27 February 2024, issued 27 February 2024, valid to 26 February 2027. Same certified scope as our quality management system. Accredited under EGAC / IAF."},
    {"img": "cert-bizsafe", "title": "bizSAFE STAR — WSH Council",
     "body": "The highest tier of Singapore's bizSAFE programme, awarded by the Workplace Safety and Health Council. Issued 14 March 2024 and valid to 26 February 2027, confirming a workplace safety and health management system assessed against national requirements."},
    {"img": "cert-aspri", "title": "ASPRI Corporate Membership",
     "body": "Corporate member of the Association of Process Industry (formerly the Process Industry Contractors' Association Singapore), membership number C0656/2011, admitted 1 June 2011 — the recognised industry body for process plant contractors on Jurong Island and beyond."},
    {"img": "cert-sws", "title": "Singapore Welding Society — Corporate Member",
     "body": "Corporate member of the Singapore Welding Society since 1 June 2011, supporting welding competence, procedure qualification and fabrication quality across our mechanical and piping scopes."},
]

FAQS = [
    ("Which industries does Pyramid Engineering work in?",
     "We work almost exclusively in process and heavy industry: refineries, petrochemical and chemical plants, power generation, renewables and solar, pharmaceutical facilities, manufacturing plants, and terminals and storage. Our ISO 9001 and ISO 45001 certificates are scoped specifically to process and industrial plant consultancy, engineering, construction and maintenance works for the chemical, refinery and petrochemical industries."),
    ("Can you work inside a live, operating plant?",
     "Yes — most of our work is executed in live plant. Our crews work to client permit-to-work systems, isolation and lock-out procedures and hazardous-area requirements as routine, and we hold bizSAFE STAR, the highest tier of Singapore's workplace safety and health programme."),
    ("Do you handle shutdowns and turnarounds?",
     "Turnaround and shutdown maintenance is one of our core lines of work. We have executed shutdown scopes at Shell Pulau Bukom, ExxonMobil Asia Pacific, the Singapore Refinery Complex, Senoko Power Station, Tuas Power Plant, Keppel Merlimau Cogen and Sembcorp Cogen Banyan, among others. Planning starts from your start-up date and works backwards."),
    ("Are you able to provide Licensed Electrical Worker (LEW) services?",
     "Yes. LEW services are offered as part of our electrical scope so that statutory sign-off is delivered with the installation rather than left as a separate procurement."),
    ("Do you supply materials as well as install them?",
     "We do. We supply electrical items, instruments, sensors and valves, insulation materials and refractory materials, and we procure construction materials for the projects we execute. Clients frequently ask us to take the supply scope so there is a single point of accountability."),
    ("Can you work as a subcontractor to a main contractor?",
     "That is how a large share of our work is delivered. We have long-standing relationships with main contractors including Kurihara Kogyo, KPW Engineering, Industrial Services, Siemens, Honeywell, Hertel, PEC, Vac-Tech and Ashahi Kokusai Keiso, and we are used to working within their project controls and reporting."),
    ("What is your typical response time for a breakdown?",
     "For clients under a call-out or long-term maintenance agreement, response commitments are defined contractually and we maintain crews familiar with the plant. For urgent unplanned work outside an existing agreement, contact us directly and we will confirm mobilisation as quickly as we can assess the scope."),
    ("How do I request a quotation?",
     "Send us your scope through the enquiry form, or email enquiry@pyramid-groups.com with drawings, specifications or a scope of work. Include the plant, the discipline, the target window and any permit or vendor pre-qualification requirements, and we will respond with clarifications or a proposal."),
]

PROCESS = [
    ("Enquiry and scope review", "We review your drawings, specifications and site constraints and come back with clarifications before pricing, not after."),
    ("Proposal and method", "A costed proposal with method statement, manpower plan, programme and the standards the work will be executed to."),
    ("Mobilisation and permits", "Risk assessments, permits, vendor pre-qualification and toolbox briefings completed before the first tool is lifted."),
    ("Execution and QA/QC", "Multi-discipline execution under supervision, with inspection and test records assembled as the work proceeds."),
    ("Commissioning and handover", "Loop checks, functional tests, energisation support and punch-list close-out with as-built documentation."),
    ("Maintenance and support", "Call-out agreements, planned maintenance and shutdown support to keep the asset running after handover."),
]

WHY_US = [
    ("Proven multi-sector track record", "Since 2008 we have delivered more than 50 documented projects across refineries, petrochemical, power, solar, pharmaceutical and manufacturing plants in Singapore.", "chart"),
    ("Integrated project management", "Electrical, C&amp;I, mechanical, insulation, refractory and civil scopes under one contractor removes the interfaces that usually cause delay.", "layers"),
    ("Skilled and certified workforce", "Experienced professionals, onsite coordinators and skilled tradesmen working under a documented health and safety policy and quality control regime.", "team"),
    ("Strong commissioning capability", "Loop checking, functional testing and start-up assistance are part of what we do, not a scope we hand to somebody else.", "check"),
    ("Reliable long-term maintenance", "Multi-year embedded maintenance relationships — Murata since 2012, Ashahi Kokusai Keiso, REC Solar, Air Liquide and others.", "clock"),
    ("Certified management systems", "ISO 9001:2015, ISO 45001:2018 and bizSAFE STAR, with ASPRI and Singapore Welding Society corporate membership.", "shield"),
]

LEGAL_PAGES = ["privacy-policy", "terms-and-conditions", "cookie-policy", "disclaimer"]
